### ISSUE TITLE
Types Definitions

### ISSUE THREAD

**Issue by dianjuar** [bajankristof/nedb-promises#13]
I'm using this package in a Typescript project and I see that you don't have any type definition 

Do you have plans to create them ?

**Comment by bajankristof** [comment]
Hi,
Actually there are type definitions in this repository, check out `index.d.ts` in the root. 
They were defined by `samdenty`: https://github.com/bajankristof/nedb-promises/pull/7
If you found this reply helpful please close the issue!
Cheers!

**Comment by kPherox** [comment]
Why latest version doesn't included `index.d.ts`?

**Comment by bajankristof** [comment]
Because I probably accidentally published from the dev branch which did not include `index.d.ts` at the time :/
Sorry for the inconvinience it is now fixed with 3.0.4
