### ISSUE TITLE
Type definitions for Cursor.exec incorrect

### ISSUE THREAD

**Issue by dylanseago** [bajankristof/nedb-promises#17]
In `index.d.ts`:
`exec(callback: (err: Error, documents: T[]) => void): void`
should be
`exec(): Promise<T[]>`

**Comment by bajankristof** [comment]
You're absolutely right, I fixed it with the 4.0.0 update. Please close the issue if this solved your problem!
https://github.com/bajankristof/nedb-promises/commit/356a605ef9044e4b34efba4b3ead18c05922a88b

**Comment by dylanseago** [comment]
Perfect, thanks!
