### ISSUE TITLE
fineOne with sort

### ISSUE THREAD

**Issue by weepy** [bajankristof/nedb-promises#18]
Hiya - I want to findOne, but say the oldest one so really I'd like to do something like 👍 

```await db.findOne({}).sort({createdAt:-1})``` 

It seems this isn't possible ?

**Comment by bajankristof** [comment]
Hi,
That's because it wasn't possible with the way I created the package originally. With the 4.0.0 update this should work now. Check it out and please close the issue if I fixed your problem!
https://github.com/bajankristof/nedb-promises/commit/356a605ef9044e4b34efba4b3ead18c05922a88b

**Comment by weepy** [comment]
wow that was good timing!
