### ISSUE TITLE
Uncaught TypeError: Unexpected object, expected: Cursor

### ISSUE THREAD

**Issue by lublank** [bajankristof/nedb-promises#20]
When I try to use the find or findOne method in the Electron renderer process, I get the error. 
It's ok in main process.

**Comment by bajankristof** [comment]
Hi, sorry for the delayed reply, autumn is always busy because of all the black fridays...
I will try to look in to this ASAP!

**Comment by bajankristof** [comment]
Are you using Vue or React in the renderer process? Because those frameworks do not preserve the class of objects when passed between components, so that could be the problem.

**Comment by lublank** [comment]
Yes, I'm using react.

**Comment by bajankristof** [comment]
Unfortunately there's nothing I can do to help that problem :/
I would suggest you ask around in the React community for help to preserve object prototypes.
