### ISSUE TITLE
findOne crashes when called on Proxy created by create()

### ISSUE THREAD

**Issue by Khaos66** [bajankristof/nedb-promises#23]
Sorry my first conclusion was not correct.
It turns out that the __original property is not resolved correctly when findOne is called on an instance created by the create() function.
When the instance is created using the new keyword everything works fine.

**Comment by bajankristof** [comment]
Sorry for the late reply. I cannot seem to reeproduce this. Can you give an example or explanation of how this can be achieved? Thanks

**Comment by bajankristof** [comment]
Closing the issue due to inactivity. Feel free to open it again in case it pops up again.
