### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by bsivanov** [bajankristof/nedb-promises#25]
I can see that the [npm package](https://www.npmjs.com/package/nedb-promises) is listed with ICS license, but still adding LICENSE file is super important [because](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Also, this would give us opportunity to include the proper copyright message and attribution when using the package as third-party dependency.

**Comment by bajankristof** [comment]
Thanks for opening this issue, I added the license in: https://github.com/bajankristof/nedb-promises/commit/f269d3c56fbd81d030eb2227b227f7e471d05e05

Also published in version 4.0.3
