### ISSUE TITLE
findOneOrCreate?

### ISSUE THREAD

**Issue by benallfree** [bajankristof/nedb-promises#27]
Are you looking for contributors? I have a few enhancements that I thought might benefit the project. Here is one:

```
  async findOneOrCreate(
    query: any,
    insert?: Partial<T>,
    projection?: Projection<T>
  ): Promise<T> {
    const rec = await this.findOne(query, projection)
    if (rec) return rec
    try {
      const newRec = await this.insert(insert || query)
      newRec.isNew = true
      return newRec
    } catch (e) {
      if (e?.errorType === 'uniqueViolated') {
        // concurrency protection
        // unique constraint violation, maybe it got inserted already
        // if it did, repeating this call should work without error
        return this.findOneOrCreate(query, insert, projection)
      }
      throw e
    }
  }
```

The motivation here is to solve for concurrency issues when using `nedb` in a server environment.  This way multiple requests to create a record will gracefully return the expected result even when called concurrently.

**Comment by bajankristof** [comment]
Hi, thanks for opening this issue! Isn't this almost the same as an upsert command with multi set to false and returnUpdatedDocs set to true?

```js
await this.update(query, insert, { upsert: true, multi: false, returnUpdatedDocs: true })
```

The only difference that I see atm is that this doesn't support projection and that it does an update even if the contents of the document weren't changed, but it's just one database operation instead of two.

**Comment by mqc507** [comment]
@bajankristof  
@benallfree 
`db.update(
    { 'username': model.username },
    { $set:
      {
        'userpwd': model.userpwd,
        'remember': model.remember
      }
    },
    {}
  )`
why always do insert data? even if set 'username' unique & WITHOUT {upsert: true}. And, has same data in db?

**Comment by bajankristof** [comment]
@benallfree sorry for the inactivity, I was thinking and also kind of busy. I think that this feature is out of the scope of this project as the purpose of this library is to allow users to work with nedb in a promisified manner without a lot of extra features. I hope that makes sense to you too!
I'm closing the issue for now for the above reasons.
