### ISSUE TITLE
store images and files

### ISSUE THREAD

**Issue by realrecordzLab** [bajankristof/nedb-promises#32]
Is possible to store images or files using this database? 
I saw on the original repo issues that this database doesn't support blob so I'm not sure if I can use it to save images or files. I like the way nedb works so if I can avoid to use indexedDB to achieve my scope it will be great.

**Comment by bajankristof** [comment]
Hi! One way to about that would be to save your data as a base64 encoded binary and then decode before using like so:
```js
// set
// https://nodejs.org/api/buffer.html
const buffer = fs.readFileSync('mypng.png')
await datastore.insert({ id: 'mypng.png', content: buffer.toString('base64') })

// get
const { content } = await datastore.findOne({ id: 'mypng.png' })
const data = new Buffer(content, 'base64')
```

**Comment by realrecordzLab** [comment]
> Hi! One way to about that would be to save your data as a base64 encoded binary and then decode before using like so:
> 
> ```js
> // set
> // https://nodejs.org/api/buffer.html
> const buffer = fs.readFileSync('mypng.png')
> await datastore.insert({ id: 'mypng.png', content: buffer.toString('base64') })
> 
> // get
> const { content } = await datastore.findOne({ id: 'mypng.png' })
> const data = new Buffer(content, 'base64')
> ```

This solution works for node, but not for the browser. Is there any solution that works for both, node and the browser?

**Comment by bajankristof** [comment]
You can do the same in the browser only the API you'll be using will be slightly different. You can use a FileReader to turn a blob into a base64 string like so: https://stackoverflow.com/questions/18650168/convert-blob-to-base64
If you don't like callbacks you could also just wrap this into a promisified function:
```js
function blobToString(blob) {
    return new Promise(function (resolve, reject) {
        var reader = new FileReader()
        reader.readAsDataURL(blob)
        reader.onloadend = function () {
            resolve(reader.result)
        }
    })
}

// and then use it
await blobToString(blob)
// non-async
blobToString(blob).then(...)
```

**Comment by bajankristof** [comment]
Please – if you're satisfied with my answer – close the issue, thanks
