### ISSUE TITLE
Implement "compaction.done" event from persistence

### ISSUE THREAD

**Issue by ismael-iskauskas** [bajankristof/nedb-promises#34]
Hello
can you implement the event compaction.done.

Proposal:
``` javascript
load() {
  if ( ! (this.__loaded instanceof Promise)) {
    this.__loaded = new Promise((resolve, reject) => {
      this.__original.loadDatabase((error) => {
        if (error) {
          this.emit('loadError', this, error)
          this.emit('__error__', this, 'load', error)
          reject(error)
        } else {
          this.emit('load', this)
          resolve()
        }
      })
    })
  }
 // NEW
  this.__original.on("compaction.done", () => {
    this.emit("compaction.done");
  });
 // NEW END
  return this.__loaded
}
```

**Comment by bajankristof** [comment]
Hi, sorry for the late reply this seems like a feature that should indeed be implemented somehow, I'll take a look at it.

**Comment by bajankristof** [comment]
I've added the feature in 4.1.0 with the difference that the event in this library is called `compactionDone` and not `compaction.done` to unify event names throughout the library.
https://github.com/bajankristof/nedb-promises/commit/3ed83d5639e9449f0e2b277eb3db39e814e12e2f
Please close the issue if you're satisfied with the update!

**Comment by ismael-iskauskas** [comment]
Cool. Thank you
