### ISSUE TITLE
Count by timestamp

### ISSUE THREAD

**Issue by yethuaungptu** [bajankristof/nedb-promises#35]
I want to find count with default timestamp 'createdAt'
#### At model
`count(day) {`
    `return this.db.count({ createdAt: { $gt: day, $lt: Date.now() } }).exec();`
  `}`

#### day timestamp
`const lastDay = moment().subtract(7, 'days').valueOf();`

#### function call
`new Promise<void>((resolve, rejects) => {`
    `maungitemstore.count(lastDay).then((result) => {`
      `console.log(result);`
      `return resolve();`
   `});`
  `});`

But return value is 0. I already inserted five document

**Comment by bajankristof** [comment]
The problem is in your `count` method:
You're invoking `Date.now()` which returns a number (the milliseconds passed since the unix epoch). Replacing this with `new Date()` (which returns a new `Date` object containing the _current_ datetime) should probably fix your issue

**Comment by bajankristof** [comment]
Closing the issue due to inactivity
