### ISSUE TITLE
How to extends Document ?

### ISSUE THREAD

**Issue by evandikt** [bajankristof/nedb-promises#38]
I create my own interface who extends Document, but i cant import { Document } from 'nedb-promises' ...
How i can do that ?

thx :1:

**Comment by bajankristof** [comment]
I'm not sure what you mean. `nedb-promises` does not export an object or function called `Document`, that's not part of the standard `nedb` library either. A document in `nedb` is just a plain old javascript object (`{}`) and not a custom class.
If you're looking for a project with classes for documents, I suggest you take a look at [nedb-models](https://github.com/bajankristof/nedb-models). I hope I answered your question, if I did please close the issue!
