### ISSUE TITLE
Q: Can I use camo with nedb-promises?

### ISSUE THREAD

**Issue by pguerrerox** [bajankristof/nedb-promises#48]
camo - https://github.com/scottwrobinson/camo

can I use it with this package, I am mainly interested in the type/validation it provides.

thanks

**Comment by bajankristof** [comment]
Hi,

I don't think that you can based on the README.md of camo, specifically this part:

> And at least ONE of the following:
> ```
> npm install nedb --save
> 
> OR
> 
> npm install mongodb --save
> ```

Also if you take a look at the code in https://github.com/scottwrobinson/camo/blob/master/lib/clients/nedbclient.js camo is directly requiring nedb, so there is no way to inject nedb-promises inside.

You could use [nedb-models](https://github.com/bajankristof/nedb-models) although that library does not provide validation out of the box, so you would have to implement that yourself.

Hope I answered your question well enough, have a great day!
