### ISSUE TITLE
TypeScript (plus suggestions and auto import in VS Code) fail due to inaccurate TypeScript declaration

### ISSUE THREAD

**Issue by jordanbtucker** [bajankristof/nedb-promises#56]
`index.d.ts` [declares a default export](https://github.com/bajankristof/nedb-promises/blob/a0d73d7690354876d435c864e2c8180889f53977/index.d.ts#L544), however nedb-promises [does not have a default export](https://github.com/bajankristof/nedb-promises/blob/a0d73d7690354876d435c864e2c8180889f53977/index.js#L1).

When using `import Datastore from 'nedb-promises'`, TypeScript will not throw an error when compiling, but the resulting JavaScript will throw an error when ran.

```ts
import Datastore from "nedb-promises"

const db = Datastore.create({filename: 'data.db'})
```

```
const db = Datastore.create({filename: 'data.db'})
                     ^

TypeError: Cannot read properties of undefined (reading 'create')
```

Note that this will not throw when `tsconfig.json` contains `esModuleInterop: true`, however this is not the default.

---

This also causes VS Code to incorrectly import nedb-promises in TypeScript and JavaScript projects.

![image](https://user-images.githubusercontent.com/468153/155252655-a55df5ff-0111-42de-a864-bda01b1dcc05.png)

![image](https://user-images.githubusercontent.com/468153/155252684-be5fa2ea-ffc0-4a75-9edf-b7142822260a.png)

Since `index.d.ts` tells VS Code that nedb-promises has a default export, VS Code suggests members that don't actually exist (because `nedbPromises.default` does not exist).

![image](https://user-images.githubusercontent.com/468153/155252897-b69de64c-3c8a-451d-b429-3cb90e166ffa.png)

```
const db = nedbPromises.create({filename: 'data.db'})
                        ^

TypeError: Cannot read properties of undefined (reading 'create')
```

When the correct `require` statement is used, VS Code displays incorrect suggestions.

![image](https://user-images.githubusercontent.com/468153/155253207-7d77dccd-ee49-450d-8260-a5a050e04402.png)

---

The solution to this is to use the `export =` syntax in `index.d.ts`. This will inform TypeScript that nedb-promises' export is not an ECMAScript Modules default export but a CommonJS export. TypeScript users must then use the `import = require()` syntax to import nedb-promises, or set `esModuleInterop: true` in `tsconfig.json` if they want to use the `import from` syntax to import nedb-promises. 

TypeScript will inform the user of this in an error message when compiling if they try to using `import from` without `esModuleInterop: true`, so this will catch the resulting runtime error before it can occur.

This will also cause VS Code to auto import nedb-promises correctly in TypeScript and JavaScript projects.

**Comment by bajankristof** [comment]
Released with `6.0.3` to NPM. Thanks again for the issue and the PR!
