### ISSUE TITLE
Package contains a reference to a license without a matching LICENSE file.

### ISSUE THREAD

**Issue by MuwuM** [bajankristof/nedb-promises#62]
Your [LICENCE](https://github.com/bajankristof/nedb-promises/blob/master/LICENSE) file states, that [nedb-promises](https://github.com/bajankristof/nedb-promises) is released under MIT License, but your [package.json](https://github.com/bajankristof/nedb-promises/blob/master/package.json) states, that it is released under ISC License.

[As recommended by socket.dev](https://socket.dev/npm/issue/mixedLicense):
A new version of the package should be published that includes a single license. Consumers may seek clarification from the package author. Ensure that the license details are consistent across the LICENSE file, package.json license field and license details mentioned in the README.

I would recommend to adjust, the package.json to

```
{
  // ...
  "license" : "MIT",
  // ...
}
```

as you reference the MIT License in the LICENSE file

**Comment by bajankristof** [comment]
Thanks for noticing the issue, I released this along some other changes with `6.1.0`
