### ISSUE TITLE
Add `updateOne` and `updateMany` over `update`

### ISSUE THREAD

**Issue by dextermb** [bajankristof/nedb-promises#64]
Hey,

I'm using `nedb-promises` for my tests, whereas live I'm using `mongodb`, recent versions of mongo have started throwing errors when using `update`:

> (node:76674) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
> (Use `node --trace-warnings ...` to show where the warning was created)

Without over engineering some alias for in my codebase I wondered if this package should be brought up to date. I'm happy to contribute if there are contribution guidelines.

Thoughts?

**Comment by dextermb** [comment]
_Bump_

**Comment by bajankristof** [comment]
Hi all!
I'm sorry for the idle time, I hope you've been playing World of Tanks in the meantime (jk).
Bad jokes aside, I hear you and today I released a new version on NPM that contains a couple of new methods:
- `insertOne`
- `insertMany`
- `updateOne`
- `updateMany`
- `deleteOne`
- `deleteMany`
I hope those solve the issue!
