### ISSUE TITLE
adding new entry on update

### ISSUE THREAD

**Issue by harvansh265** [bajankristof/nedb-promises#68]
I am new to use nedb-promises and I am facing issue that , when  I am updating any record that's inserting a new record with same id

**Comment by bajankristof** [comment]
Hi! On the file-system level, this is expected. When reading from the datastore you should still see only one document however. If you want to have only a single document in the stored file as well, you need to compact the datastore using `datastore.persistence.compactDatafile()` or set an auto-compaction interval using `datastore.persistence. setAutocompactionInterval(interval)`.
